pipeline {
    agent any

    environment {
        VENV = 'venv'
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/your-username/your-django-repo.git'
            }
        }

        stage('Set Up Python Environment') {
            steps {
                sh '''
                    python3 -m venv $VENV
                    source $VENV/bin/activate
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Lint & Format') {
            steps {
                sh '''
                    source $VENV/bin/activate
                    flake8 .
                    black --check .
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    source $VENV/bin/activate
                    pytest --ds=your_project.settings --junitxml=test-results.xml --cov=.
                '''
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('infra') {
                    sh '''
                        terraform init
                        terraform apply -auto-approve
                    '''
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                sh '''
                    ssh -i key.pem ec2-user@<ec2-public-ip> 'bash deploy.sh'
                '''
            }
        }
    }

    post {
        always {
            junit 'test-results.xml'
        }
    }
}
